name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - user: actions/checkout@v2
    -name: Set up JDK 11
    users: actions/setup-java@v2
    with:
      java-version: '11'
      distribution: 'adopt'
    - name: Build with Maven
     run: mvn -B -e verify
